server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker 컨테이너 로그
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Spring Boot 애플리케이션 로그 (JSON 형식)
  - job_name: spring-boot-json
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          log_type: json
          __path__: /var/log/practice-board/application.json

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            message: message
            exception: exception
      - timestamp:
          format: 2006-01-02T15:04:05.000Z0700
          source: timestamp
      - labels:
          level:
          logger:
      - output:
          source: message

  # Spring Boot 애플리케이션 로그 (표준 형식)
  - job_name: spring-boot-standard
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          log_type: standard
          __path__: /var/log/practice-board/app.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>[^\]]+)\] (?P<level>\w+) +(?P<logger>[^\s]+) - (?P<message>.*)'
      - timestamp:
          format: '2006-01-02 15:04:05.000'
          source: timestamp
      - labels:
          level:
          thread:
          logger:
      - output:
          source: message

  # MySQL 로그
  - job_name: mysql
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql
          service: database
          __path__: /var/log/mysql/*.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?P<level>\w+) (?P<message>.*)'
      - timestamp:
          format: '2006-01-02T15:04:05.000000Z'
          source: timestamp
      - labels:
          level:
      - output:
          source: message

  # Nginx 액세스 로그
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          log_type: access
          service: loadbalancer
          __path__: /var/log/nginx/access.log

    pipeline_stages:
      - regex:
          expression: '(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" "(?P<http_x_forwarded_for>[^"]*)" rt=(?P<request_time>\S+) uct="(?P<upstream_connect_time>[^"]*)" uht="(?P<upstream_header_time>[^"]*)" urt="(?P<upstream_response_time>[^"]*)"'
      - timestamp:
          format: '02/Jan/2006:15:04:05 -0700'
          source: time_local
      - labels:
          method:
          status:
          remote_addr:
      - output:
          source: message

  # Nginx 에러 로그
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          log_type: error
          service: loadbalancer
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<message>.*)'
      - timestamp:
          format: '2006/01/02 15:04:05'
          source: timestamp
      - labels:
          level:
      - output:
          source: message

  # 시스템 로그
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          service: system
          __path__: /var/log/syslog